export { default as Authentification } from "./Authentification";
export { default as Home } from "./Home";
export {default as Registration } from "./Registration";
export {default as PassworChange } from "./PasswordChange";
export { default as Challenge } from './Challenge';
export { default as Associations } from './Associations';
export { default as Donor } from './Donor';
export { default as Team } from './Team';
export { default as Profil } from './Profil';
export { default as  LogOutView} from './LogOut';